vocab_size = 32000  # Number of unique tokens in the vocabulary
max_seq_len = 256  # Maximum sequence length
d_model = 384  # Transformer hidden size / embedding dimension
n_heads = 6  # Size of attention heads in multi-head self-attention
n_layers = 12  # Size of Transformer blocks
d_ff = 1536  # Hidden dimension of the FFN
dropout = 0.1  # Dropout probability applied during training
batch_size = 16  # Training batch size
lr = 2e-4  # Learning rate for the optimizer.
weight_decay = 0.01  # weight decay
epochs = 20  # Number of full passes over the training dataset
classification_epochs = 3  # Number of fine-tuning epochs for IMDb classification
max_steps_per_epoch = 10000 # steps of each epoch
warmup_steps = 3000  # Warmup steps for the learning-rate schedule
device = "cuda"  # GPU
